name: "Release and Deploy"

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches: ["main"]

permissions:
  id-token: write
  contents: write
  actions: read
  
jobs:
  release:
    name: Tag and release
    runs-on: ubuntu-latest
