name: "Build and Test"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: 
      - 'test'

permissions:
  contents: read

jobs:
  build:
    name: Docker build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
