name: "Release and Deploy"

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches: ["main"]
    
permissions:
  contents: read

jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest

    steps:
      - name: Start Release
        run: echo "Release triggered by Build Workflow!"

      - name: Deploy
        run: echo "Deploying the project..."
