name: "Release and Deploy"

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches: ["main"]
  
jobs:
  release:
    name: Tag and release
    runs-on: ubuntu-latest
